[platformio]
default_envs = field_relay

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -I../common

[env:field_relay]
build_flags =
  ${env.build_flags}
  -DCURRENT_NODE_ID=RELAY_NODE_DRONE_1
  -DENABLE_FORWARDING=1

[env:field_leaf]
build_flags =
  ${env.build_flags}
  -DCURRENT_NODE_ID=RELAY_NODE_DRONE_2
  -DENABLE_FORWARDING=0
